// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package cdb

import (
	"context"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens
    (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type CreateTokenParams struct {
	UserID    string
	Token     string
	ExpiresAt int64
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteTokensByUserId = `-- name: DeleteTokensByUserId :exec
DELETE
FROM tokens
WHERE user_id = ?
`

func (q *Queries) DeleteTokensByUserId(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUserId, userID)
	return err
}

const getToken = `-- name: GetToken :one
SELECT user_id, token, expires_at
FROM tokens
WHERE token = ?
  AND expires_at > ?
`

type GetTokenParams struct {
	Token     string
	ExpiresAt int64
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, arg.Token, arg.ExpiresAt)
	var i Token
	err := row.Scan(&i.UserID, &i.Token, &i.ExpiresAt)
	return i, err
}

const getTokensByUser = `-- name: GetTokensByUser :many
SELECT user_id, token, expires_at
FROM tokens
WHERE user_id = ?
`

func (q *Queries) GetTokensByUser(ctx context.Context, userID string) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(&i.UserID, &i.Token, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
