// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package cdb

import (
	"database/sql"
)

type Chore struct {
	ID             string
	Name           string
	Interval       int64
	LastCompletion int64
	SnoozedFor     int64
	CreatedAt      int64
	ChoreListID    string
	CreatedBy      string
}

type ChoreEvent struct {
	ID         string
	ChoreID    string
	OccurredAt int64
	EventType  string
	CreatedBy  string
}

type ChoreList struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
	Name      string
}

type ChoreListMember struct {
	ChoreListID string
	UserID      string
}

type Invitation struct {
	ID          string
	CreatedAt   int64
	ExpiresAt   int64
	ChoreListID sql.NullString
	CreatedBy   string
}

type PasswordAuth struct {
	UserID   string
	Username string
	Hash     string
}

type Token struct {
	UserID    string
	Token     string
	ExpiresAt int64
}

type User struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
}
